name: Publish

on:
  pull_request:
    branches: [ "dev" ]
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged && ( contains( "no-publish", github.event.pull_request.labels ) == false )
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Publish
      run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
